CC = gcc
PYTHON = python3

BUILD_DIR = build
CMAKE_BUILD_TYPE ?= Release

WEIGHTS_PATH = data/weights.bin
IMAGE_PATH = data/image.bin
OUTPUT_FILE = data/output.txt
OUTPUT_STD_FILE = data/output.std.txt
ORIGIN_IMAGE_PATH = data/image.png
ORIGIN_IMAGE_URL = https://s3.amazonaws.com/model-server/inputs/kitten.jpg

MAKEFLAGS += --no-print-directory # suppress entering or leaving directory messages

.PHONY: build configure clean run data test

build: configure
	cmake --build $(BUILD_DIR)

configure:
	cmake -B $(BUILD_DIR) -DCMAKE_C_COMPILER=$(CC) -DCMAKE_BUILD_TYPE=$(CMAKE_BUILD_TYPE)

clean:
	rm -rf $(BUILD_DIR)

run: build data
	$(BUILD_DIR)/vgg11_bn $(WEIGHTS_PATH) $(IMAGE_PATH) $(OUTPUT_FILE)

test:
	@echo "diff $(OUTPUT_FILE) (generated by vgg11_bn) and $(OUTPUT_STD_FILE) (generated by pytorch), and eps is setting to 1e-5"
	@make run >/dev/null 2>&1
	@$(PYTHON) test/test.py $(ORIGIN_IMAGE_PATH) $(OUTPUT_STD_FILE)
	@$(PYTHON) test/diff.py $(OUTPUT_FILE) $(OUTPUT_STD_FILE)

data: $(WEIGHTS_PATH) $(IMAGE_PATH)

$(WEIGHTS_PATH): data/weights.py
	$(PYTHON) data/weights.py $(WEIGHTS_PATH)

$(IMAGE_PATH): data/image.py $(ORIGIN_IMAGE_PATH)
	$(PYTHON) data/image.py $(ORIGIN_IMAGE_PATH) $(IMAGE_PATH)

$(ORIGIN_IMAGE_PATH):
	curl -o $(ORIGIN_IMAGE_PATH) $(ORIGIN_IMAGE_URL)
